### ISSUE TITLE
SJPv4 html file - values coming undefined and panchang is also wrong

### ISSUE THREAD

**Issue by vaishalithaker** [SanjayPrabhakaran/srijagannatha-panchanga#14]
Hi,

I downloaded the project and was checking html file from SJPV4 folder. i see all values are undefined. 

Could you please resolve this issue or provide appropriate solution. Screenshot attached for reference
![undefined values](https://user-images.githubusercontent.com/45140624/160858033-c55f1c3c-f76e-4c64-ad91-72a5b2447123.jpg)

**Comment by SanjayPrabhakaran** [comment]
Download latest version
